package com.documaster.rms.noark.ws.constants;

public enum EInnsynState {

	NOT_PUBLISHED,
	READY_FOR_PUBLISHING_METADATA,
	READY_FOR_PUBLISHING_METADATA_AND_DOCUMENTS,
	READY_FOR_UNPUBLISHING,
	IN_PROGRESS_PUBLISHING_METADATA,
	IN_PROGRESS_PUBLISHING_METADATA_AND_DOCUMENTS,
	IN_PROGRESS_UNPUBLISHING,
	PUBLISHED_METADATA,
	PUBLISHED_METADATA_AND_DOCUMENTS,
	FAILED_TO_PUBLISH,
	FAILED_TO_UNPUBLISH,
	CONTAINS_SENSITIVE_METADATA
}